language: python
python:
  - "3.5"

services:
  - docker

env:
  - BROKER_URI=amqp://infrabbit3:infrabbit3@$localhost/

before_install:
  - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
  - sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
  - docker run -d --hostname infrabbit3 --name infrabbit3 -e RABBITMQ_DEFAULT_USER=infrabbit3 -e RABBITMQ_DEFAULT_PASS=infrabbit3 -p 15672:15672 -p 5672:5672 aleasoluciones/rabbitmq-delayed-message:0.2

install:
  - python setup.py develop
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - sleep 20
  - ./dev/all_tests.sh
